using System.Collections;
using System.Collections.Generic;
using UnityEngine.UI;
using UnityEngine;

public class InGameNotificaion : MonoBehaviour
{
	public GameObject BlockMenu;
	public GameObject WelcomeMenu;

	//On Awake
	private void Awake ()
	{
		WelcomeMenu.SetActive (true);
		BlockMenu.SetActive (false);
	}

	//Welcome Menu Options
	public void OnPlayClick ()
	{
		WelcomeMenu.SetActive (false);
	}

	//Block Menu Options
	public void OnContinueClick ()
	{
		BlockMenu.SetActive (false);
	}
}
